import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import styles from "..//styles/Home.module.css";
import Leftside from "@/components/Leftside";
import About from "@/components/About";
import { motion } from "framer-motion";
import Header from "@/components/Header";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hugo Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/hache.ico" />
      </Head>
      <main className={styles.container}>
        <Navbar />
        <div className={styles.body}>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className={styles.leftsideContainer}
          >
            <Leftside />
          </motion.div>
          <div className={styles.center}>
            <Header />
            <About />
            <Projects />
            <Contact />
          </div>
        </div>
      </main>
    </div>
  );
}
