import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import styles from "..//styles/Home.module.css";
import Leftside from "@/components/Leftside";
import About from "@/components/About";
import { motion } from "framer-motion";
import Header from "@/components/Header";
import Experience from "@/components/Experience";
import Projets from "@/components/Projets";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hugo Portfolio</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,800&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Navbar />
        <div className={styles.body}>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className={styles.leftsideContainer}
          >
            <Leftside />
          </motion.div>
          <div className={styles.center}>
            <Header />
            <About />
            <Experience />
            <Projets />
            <Contact />
          </div>
        </div>
      </main>
    </div>
  );
}
